services:
  db:
    image: mariadb:10.7.3
    container_name: maria
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: CMSDB
      MYSQL_USER: principal
      MYSQL_PASSWORD: secret
    ports:
      - "3333:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always

  website:
    container_name: cmsapp
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: CMSDB
      DB_USERNAME: principal
      DB_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html

volumes:
  db:
